name: elevators
favicon: null
layout_spectrum: 0.2793013059999794
typography_spectrum: 0.8688932752702385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1445029228925705
  lightness: 0.7041552537120879
  saturation: 0.9246089209336787
  rhythmicContrast: 0.5276791465003043
purpose: []
